export const environment = {
  production: true,
  env: 'cf',
  url_base_site: 'https://celufio.mx',
  incode_apikey: '9baf4f2f0baad30988802538abf3e707b2c9721b',
  incode_clientid: 'celucenter435',
  incode_apiurl: 'https://saas-api.incodesmile.com',
  incode_flowSaleId: '638a7726479e907abb63e473',
  incode_pagoAnticipado: '64a6d6ef34947aab082c5dbd',
  incode_flow_gt_sale: '65dd1af1cf81d3be091b62ea',
  process_with_incode: false,
  process_with_nubarium: true,
  process_capture_manual: true,
  url_extends_local: false,
  incode_scoretrue: 90,
  tokensurl: 'bfb3f439053d298f06d221f735ae531cf7e3b',
  url_api_cf: 'https://api.celufio.mx',
  url_api_cfv: 'https://validate.celufio.mx',
  url_api_cfws: 'https://aplws.celufio.mx',
  url_api_cel: 'https://api.celucenter.com',
  url_ws: 'wss://41n03a2b1e.execute-api.us-east-2.amazonaws.com/production',
  process_with_cc: 1,
  process_with_cc_value: 80,
  process_with_incode_start: 1,
  process_with_conekta: 1,
  version: '2.0.0',
  msg_alert_branch_bool: true,
  COMPANY_NAME: "payphone",
  email_contacto:"mailto:contacto@celufio.mx",
  email_cumplimiento_legal:"mailto:legalcompliance@incode.com"
};
